name: CI/CD Pipeline

on:
  push:
    branches:
      - Tes
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Build Docker Containers
        run: docker-compose up -d --build

  sast:
    name: SAST Stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run PHP Static Analysis (PHPStan)
        run: |
          cd TugasCRUD
          composer require --dev phpstan/phpstan
          vendor/bin/phpstan analyse --level=max .

  dast:
    name: DAST Stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: http://localhost:8080
