name: CI/CD Pipeline

on:
  push:
    branches:
      - Tes
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Build Docker Containers
        run: docker-compose up -d --build

  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: db_mahasiswa
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mysqli

      - name: Debug Directories
        run: |
          echo "Current directory:"
          pwd
          echo "List of files:"
          ls -la

      - name: Install Dependencies
        run: |
          cd TugasCRUD  # Pindah ke direktori tempat composer.json berada
          composer install

      - name: Run PHPUnit
        run: |
          cd TugasCRUD  # Pindah ke direktori tempat phpunit.xml berada
          vendor/bin/phpunit --configuration phpunit.xml

