name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature-ci-pipeline
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode
      - name: Checkout Code
        uses: actions/checkout@v3

      # Langkah 2: Build Stage
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      # Langkah 3: Security Scanning dengan Bandit
      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          # Scan seluruh direktori secara rekursif dan hentikan pipeline jika ada severity HIGH atau CRITICAL
          bandit -r . --severity-level high || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
      # Deploy aplikasi ke staging
      - name: Deploy to Staging
        run: |
          docker-compose -f docker-compose.staging.yml down
          docker-compose -f docker-compose.staging.yml up -d
