name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature-ci-pipeline
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode
      - name: Checkout Code
        uses: actions/checkout@v3

      # Langkah 2: Install Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Langkah 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Langkah 4: Build Stage
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      # Langkah 5: Run Unit Tests
      - name: Run Unit Tests
        run: |
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit

      # Langkah 6: Security Scanning dengan Bandit
      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          bandit -r . --severity-level high || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
      # Deploy aplikasi ke staging
      - name: Deploy to Staging
        run: |
          docker-compose -f docker-compose.staging.yml down
          docker-compose -f docker-compose.staging.yml up -d
