name: CI/CD Pipeline

on:
  push:
    branches:
      - Tes
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Containers
        run: docker-compose up -d --build

  test:
    name: Test Stage
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: db_mahasiswa
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mysqli

      - name: Install Dependencies
        run: composer install

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml
